# -*- coding: utf-8 -*-
"""Assignment8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jTfH3QivHFw42J61c1b2t2JLXvzZ3_kC
"""

#Program to balance a chemical equation using echelon matrix
 
import numpy as np
import sympy
 
 
#if using termux
#import subprocess
#import shlex
#end if
 
#Coefficient Matrix
A= np.array([[1,0,-2,0], [1,4,-4,-1], [1,2,0,-2], [0,1,-1,0]])
#Row reduced echelon form
print("The row reduced echelon form of the matrix and pivot columns are: ")
print(sympy.Matrix(A).rref())